#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
#pragma config(Motor,  motorA,          lewy,          tmotorEV3_Large, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          lewy1,         tmotorEV3_Large, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          prawy1,        tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorD,          prawy,         tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define moc 90          // 80    90   najlepsze na trudne trasy [90,1.9,2.7,6]
int Autyzm=3;                        //2      najlepsze na trudne trasy [3]
int sen_zew1,sen_wew1,sen_wew2,sen_zew2,lewa_strona,prawa_strona,lewa_moc,prawa_moc,czarny_sensor;
int ostatni_czarny = 0;
float Korekta,jedziemy;
float Ostatnia_Korekta_lewa = 0;
float Ostatnia_Korekta_prawa = 0;
float srednia_SENSORY;

task liczydelko()
{
 srednia_SENSORY=((SensorValue[S1]+SensorValue[S2]+SensorValue[S3]+SensorValue[S4])/4)-30;
  if(czarny_sensor!=0){ostatni_czarny=czarny_sensor;}

	if(SensorValue[S1]<srednia_SENSORY){czarny_sensor=1;}

	if(SensorValue[S2]<srednia_SENSORY){czarny_sensor=2;}

	if(SensorValue[S3]<srednia_SENSORY){czarny_sensor=3;}

	if(SensorValue[S4]<srednia_SENSORY){czarny_sensor=4;}

	if(SensorValue[S1]<srednia_SENSORY && SensorValue[S2] < srednia_SENSORY){czarny_sensor=12;}

	if(SensorValue[S4]<srednia_SENSORY && SensorValue[S3] < srednia_SENSORY){czarny_sensor=34;}

	if(SensorValue[S1]>srednia_SENSORY&&SensorValue[S2]>srednia_SENSORY&&SensorValue[S3]>srednia_SENSORY&&SensorValue[S4]>srednia_SENSORY){czarny_sensor=0;}
  if(czarny_sensor==1||czarny_sensor==4||czarny_sensor==0||czarny_sensor==12||czarny_sensor==34){Autyzm=1.9;} // [1.8]  [1.6]
  if(czarny_sensor==2||czarny_sensor==3){Autyzm=2.7;}       // [3]    [2.8]    |


}
task liczonko()
{
	sen_zew1=SensorValue[S1];
	sen_wew1=SensorValue[S2];
	sen_wew2=SensorValue[S3];
	sen_zew2=SensorValue[S4];

	sen_zew1=sen_zew1;
	sen_zew2=sen_zew2;

	lewa_strona=sen_zew1+sen_wew1;
	prawa_strona=sen_zew2+sen_zew2;

	Korekta=(lewa_strona-prawa_strona);

	if(Korekta<Ostatnia_Korekta_lewa){Ostatnia_Korekta_lewa=Korekta;}                          // lewa strona sensorów to warto?a ujemna
	if(Korekta>Ostatnia_Korekta_prawa){Ostatnia_Korekta_prawa=Korekta;}                       // prawa strona sensorów to wartosa dodatnia
	if(czarny_sensor==0&&ostatni_czarny==1){Korekta=Ostatnia_Korekta_lewa;}
	if(czarny_sensor==0&&ostatni_czarny==4){Korekta=Ostatnia_Korekta_prawa;}

}
task Pomykamy()
{
  jedziemy=moc-((Korekta/Autyzm)/6);
	lewa_moc=jedziemy+Korekta/Autyzm;
	prawa_moc=jedziemy-Korekta/Autyzm;
	if(lewa_moc<0)
	{
		lewa_moc=0;
	}
	if(prawa_moc<0)
	{
		prawa_moc=0;
	}
	setMotorSpeed(lewy,lewa_moc);
	setMotorSpeed(prawy,prawa_moc);
	setMotorSpeed(lewy1,lewa_moc);
	setMotorSpeed(prawy1,prawa_moc);


}



task main()
{
	while(666)
	{
		startTask (liczydelko);
		startTask (liczonko);
		startTask (Pomykamy);
		displayCenteredTextLine(1, "czarny_numerek: %d", czarny_sensor);
		displayCenteredTextLine(2, "ostatni_czarny:	  %d", ostatni_czarny);
		displayCenteredTextLine(3, "Korekta:	  %d", Korekta);
		displayCenteredTextLine(4, "lewa_moc:	  %d", lewa_moc);
		displayCenteredTextLine(5, "prawa_moc:	  %d", prawa_moc);
	}

}
